plugins:
  - jest

env:
  node: true
  jest: true
  browser: true
  es2021: true

parserOptions:
  ecmaVersion: 12
  sourceType: module

extends:
  - "airbnb-base"
  - "plugin:jest/recommended"

rules:
  import/extensions: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
